# Set charset to UTF-8
charset utf-8

# Enable smartcard support
use-agent

# Display all keys and their fingerprings
with-fingerprint
with-keygrip

fixed-list-mode

personal-cipher-preferences AES256 AES192 AES
personal-digest-preferences SHA512 SHA384 SHA256
personal-compress-preferences ZLIB BZIP2 ZIP Uncompressed
default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
cert-digest-algo SHA512
s2k-digest-algo SHA512
s2k-cipher-algo AES256

# Disable software information versions
no-greeting
no-comments
no-emit-version

# Key format
keyid-format 0xlong

# Disaplay UID
list-options show-uid-validity
verify-options show-uid-validity


# When verifying a signature made from a subkey, require that the
# cross certification "back signature" on the subkey is present and valid
# This protects against a subtle attack against subkeys that can sign
require-cross-certification

# Does not put the recipient key IDs into encrypted messages
# This helps to hide the receivers of the message and is a limited
# countermeasure against traffic analysis
throw-keyids

# Set the default key use when signing
default-recipient-self

# Disable caching of passphrase for symmetrical encryption and decryption
no-symkey-cache

# Set this to get more info
verbose 
