[tools]
age = "latest"
atuin = "latest"
bat = "latest"
btop = "latest"
chezmoi = "latest"
claude-code = "latest"
cocogitto = "latest"
cosign = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
hcloud = "latest"
lazygit = "latest"
ripgrep = "latest"
slsa-verifier = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
